# Trabalho 2: Filogenia

Leonardo Azzi Martins

# Questão 1

a) Descubra o organismo correspondente de cada uma das 10 sequência (dica: usar o Blast para esta tarefa, https://blast.ncbi.nlm.nih.gov/Blast.cgi).

Formato da Resposta:

seq_1: Streptococcus agalactiae

seq_2: Neisseria gonorrhoeae

seq_3: Mycobacterium tuberculosis

seq_4: Staphylococcus aureus

seq_5: Treponema pallidum

seq_6: Bacillus anthracis

seq_7: Yersinia pestis

seq_8: Acinetobacter baumannii 

seq_9: Pseudomonas aeruginosa

seq_10: Helicobacter pylori

b) Realize o alinhamento global par-a-par de todas as sequências entre si. Para esta tarefa deve ser utilizado o algoritmo Needleman e Wunsch implementado no Trabalho I da disciplina. Você deve reportar o score de cada alinhamento considerando o seguinte esquema de pontuação: Match = +1; Mismatch = -1; Gap = -2.

Formato da Resposta:

seq_1 vs seq_2: xxx
seq_1 vs seq_3: xxx
…
seq_10 vs seq_9: xxx

In [1]:
import numpy as np
sequences_ids = list(range(1, 11))
matrix_size = len(sequences_ids)

distance_matrix = np.zeros((matrix_size, matrix_size))

In [2]:
# b)
import global_alignment
import numpy as np

dir = "./2_phylogenetics"
format = "fasta"
id1 = "seq_1"
id2 = "seq_2"
scoring_file = "scoring"

sequences_ids = list(range(1, 11))
num_of_seqs = len(sequences_ids)

distance_matrix = np.zeros((num_of_seqs, num_of_seqs))

for target_id in sequences_ids:
    print("Alvo:", target_id)

    candidates_ids = sequences_ids.copy()
    candidates_ids.remove(target_id)
    print("Candidatos:", candidates_ids)

    for candidate_id in candidates_ids:
        print(f"\nseq_{target_id} vs seq_{candidate_id}\n-----------------------------------------------------------------")
        result = global_alignment.main(dir, format, f"seq_{target_id}", f"seq_{candidate_id}", scoring_file)
        print(result)

        # c)
        distance_matrix[target_id - 1, candidate_id - 1] = result["score"]
        distance_matrix[candidate_id - 1, target_id - 1] = result["score"]

    print("\n====================================================================================================\n")

    distance_matrix

Alvo: 1
Candidatos: [2, 3, 4, 5, 6, 7, 8, 9, 10]

seq_1 vs seq_2
-----------------------------------------------------------------
{'seq_1': 'AAAC-ACCTCCAGTCATAAT-A-TTCGTAAACCAATCAAAAACTCATGTTTTAAATCAATAAAAAATACTTAG-', 'seq_2': 'CCCCTGCCGATTTTCGGAGTCAGACCGT-GCGTAATATAAAACGC-CG--GCCCGCCGATGTATTTGCCGTGGC', 'score': -26, 'identity': 0.3783783783783784, 'match': 28}

seq_1 vs seq_3
-----------------------------------------------------------------
{'seq_1': '-AAACAC-CTCCAGTCATAATATTCGTAAACCAATCAAAAACTCA-TGTTTTAAATCAATAAAAAAT-ACTTA-G', 'seq_2': 'TCACCACGCCCCCACGACGGAGCTCGT-GGGC-ACCCAGCATTCACTG-CTT--ACCACTACGATCTCGCTCACG', 'score': -15, 'identity': 0.4666666666666667, 'match': 35}

seq_1 vs seq_4
-----------------------------------------------------------------
{'seq_1': 'AAACACCTCCAGTCATAATATTCGT-AAACCAATCAAAAACTCAT-GTTTTAAATCAATA-AAAAATACTTAG', 'seq_2': 'TTATTTTGAAAGTAACAAT-GGCATCATTATTATTAAATGGT-ATAGGTTT-CTTGTTTACTGGTATGCTTCA', 'score': -17, 'identity': 0.4246575342465753, 'match': 31}

se

c) Utilize o score de cada alinhamento obtido na letra “b” e construir uma matriz de distância entre as 10 OTUs.

Formato da Resposta:

seq_1 seq_2 seq_3 seq_4 seq_5 seq_6 seq_7 seq_8 seq_9 seq_10

seq_1

seq_2

seq_3

seq_4

seq_5

seq_6

seq_7

seq_8

seq_9

seq_10

In [6]:
print(distance_matrix)

[[  0. -26. -15. -17. -17. -13. -25. -20. -29. -11.]
 [-26.   0. -19. -27. -23. -24. -15. -20. -10. -23.]
 [-15. -19.   0. -22. -11. -16. -14. -32.  -6. -19.]
 [-17. -27. -22.   0. -23. -10. -17. -23. -32. -13.]
 [-17. -23. -11. -23.   0. -17.  -6. -18.  -4. -16.]
 [-13. -24. -16. -10. -17.   0. -18. -26. -24. -23.]
 [-25. -15. -14. -17.  -6. -18.   0. -26. -15. -15.]
 [-20. -20. -32. -23. -18. -26. -26.   0. -34. -14.]
 [-29. -10.  -6. -32.  -4. -24. -15. -34.   0. -21.]
 [-11. -23. -19. -13. -16. -23. -15. -14. -21.   0.]]


d) Implemente o algoritmo UPGMA (unweighted pair group method with arithmetic mean) para realizar a construção da árvore filogenética das 10 OTUs consideradas na letra “a”

Entrada do algoritmo: matriz de distâncias construída no item “c”

In [ ]:
print(distance_matrix)
np.savetxt(f'{dir}/q1_matrix.txt', distance_matrix, fmt='%d')


[[  0. -26. -15. -17. -17. -13. -25. -20. -29. -11.]
 [-26.   0. -19. -27. -23. -24. -15. -20. -10. -23.]
 [-15. -19.   0. -22. -11. -16. -14. -32.  -6. -19.]
 [-17. -27. -22.   0. -23. -10. -17. -23. -32. -13.]
 [-17. -23. -11. -23.   0. -17.  -6. -18.  -4. -16.]
 [-13. -24. -16. -10. -17.   0. -18. -26. -24. -23.]
 [-25. -15. -14. -17.  -6. -18.   0. -26. -15. -15.]
 [-20. -20. -32. -23. -18. -26. -26.   0. -34. -14.]
 [-29. -10.  -6. -32.  -4. -24. -15. -34.   0. -21.]
 [-11. -23. -19. -13. -16. -23. -15. -14. -21.   0.]]


Saída: a árvore filogenética

**Os índices das sequências começam em 0.**

seq_1 -> 0, 

seq_2 -> 1, 

...

In [11]:
import upgma
upgma.run(distance_matrix)

(4, ((6, ((3, (8, 7)), (1, 0))), (2, (9, 5))))